### ISSUE TITLE
standalone false option

### ISSUE THREAD

**Issue by Plus17** [joshnuss/xml_builder#49]
Hi, thanks for your work with XML builder :)

Currently, we have an issue with the `standalone` option. We are consuming a service that, apparently breaks if we don't send the `standalone` with `no` value:

```xml
<?xml version="1.0" standalone="no"?>
```

Do you consider implementing this behavior when explicitly pass a `false` value? Something like:

```elixir
import XmlBuilder

document(:outsider)
|> generate(standalone: false)
```

Output:

```xml
<?xml version="1.0" standalone="no"?>
<outsider/>
```

**Comment by joshnuss** [comment]
Hi @Plus17,

You are most welcome,

I think we should support `standalone="no"` option. 

Would you like to open a PR? 

Essentially, we should support 3 ways:

- `generate(..., standalone: false)` => `standalone="no"`
- `generate(..., standalone: true)` => `standalone="yes"`
- `generate(..., standalone: nil)` => no standalone attribute

Default should change to `nil`.

It's slightly breaking change, since previous default was `false`, but I think we can just mention it in the changelog and do a minor point release.

**Comment by Plus17** [comment]
> Would you like to open a PR? 

sure, i will tackle this

**Comment by joshnuss** [comment]
Added in #50
